import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm, symlink, lstat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer } from 'node:net';
import { execFileSync } from 'node:child_process';

const dir = await mkdtemp(join(tmpdir(), 'aios-disk-cleanup-'));
const portProbe = createServer();
await new Promise(resolve => portProbe.listen(0, '127.0.0.1', resolve));
const port = portProbe.address().port;
await new Promise(resolve => portProbe.close(resolve));
process.env.AIOS_DATA = join(dir, 'data'); process.env.AIOS_WORKTREE_ROOT = join(dir, 'worktrees');
const tmuxFixture = join(dir, 'tmux-fixture.sh');
await writeFile(tmuxFixture, '#!/bin/sh\nprintf "no server running on private cleanup fixture\\n" >&2\nexit 1\n', { mode: 0o755 });
process.env.AIOS_TMUX = tmuxFixture; process.env.AIOS_HOST = '127.0.0.1'; process.env.AIOS_PORT = String(port);
process.env.AIOS_SUMMARY_PORT = '1'; delete process.env.AIOS_NO_LISTEN;
let store;
const base = `http://127.0.0.1:${port}`;
const post = async (path, body) => { const res = await fetch(base + path, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); return { status: res.status, body: await res.json() }; };
const exists = path => lstat(path).then(() => true, () => false);
const project = join(dir, 'project');
try {
  const { featureReady } = await import('../src/server.js'); await featureReady;
  store = await import('../src/store.js');
  const { sessionStoragePaths, prepareSessionStorage } = await import('../src/session_storage.js');
  const capacityResponse = await fetch(base + '/api/product/storage/capacity');
  assert.equal(capacityResponse.status, 200);
  const capacitySnapshot = await capacityResponse.json();
  assert.ok(Number.isFinite(capacitySnapshot.capacity.available_bytes));
  assert.ok(Number.isFinite(capacitySnapshot.database.reusable_bytes));
  assert.equal(capacitySnapshot.sessions, undefined, 'cheap capacity endpoint never downloads the session inventory');
  await mkdir(project); await writeFile(join(project, 'keep-code'), 'important code');
  store.createProject({ id: 'p_disk', name: 'Disk fixture', path: project });
  async function fixture(id, reason = 'operator-kill') {
    store.createSession({ id, project_id: 'p_disk', tool: 'codex', tmux: `fixture-${id}`, status: 'exited' });
    store.updateSession(id, { status_reason: reason });
    store.addMessage(id, 'in', 'task', 'Keep the original request unless I confirm deletion.');
    const paths = await prepareSessionStorage(id);
    await writeFile(join(paths.tmp, 'qa.txt'), 'discardable'); await writeFile(join(paths.artifacts, 'result.txt'), 'durable output');
    await writeFile(join(process.env.AIOS_DATA, 'logs', `${id}.log`), 'terminal history');
    const shots = join(process.env.AIOS_DATA, 'supervisor', id);
    await mkdir(join(shots, 'profile'), { recursive: true });
    await writeFile(join(shots, 'review.png'), 'saved review evidence');
    await writeFile(join(shots, 'profile', 'cache'), 'disposable browser cache');
    return paths;
  }
  const kept = await fixture('s_disk_kept');
  let r = await post('/api/product/storage/plan', { sessions: ['s_disk_kept'], mode: 'disposable' });
  assert.equal(r.status, 200); const plan = r.body;
  assert.ok(plan.sessions[0].targets.every(t => ['logs', 'scratch', 'launch', 'browser-cache'].includes(t.kind)));
  assert.equal((await post('/api/product/storage/cleanup', { plan_id: plan.id })).status, 400);
  assert.equal(await exists(kept.tmp), true, 'preview/unconfirmed cleanup is read-only');
  r = await post('/api/product/storage/cleanup', { plan_id: plan.id, confirm: true });
  assert.equal(r.body.ok, true); assert.equal(await exists(kept.root), false);
  assert.equal(typeof r.body.capacity_before.available_bytes, 'number');
  assert.equal(typeof r.body.capacity_after.available_bytes, 'number');
  assert.equal(r.body.net_available_change_bytes, r.body.capacity_after.available_bytes - r.body.capacity_before.available_bytes,
    'filesystem delta is measured separately, not equated with estimated removed files');
  const receipt = r.body;
  assert.equal(await readFile(join(kept.artifacts, 'result.txt'), 'utf8'), 'durable output');
  assert.equal(await readFile(join(process.env.AIOS_DATA, 'supervisor', 's_disk_kept', 'review.png'), 'utf8'), 'saved review evidence');
  assert.equal(await exists(join(process.env.AIOS_DATA, 'supervisor', 's_disk_kept', 'profile')), false);
  assert(store.getSession('s_disk_kept')); assert.equal(store.messagesFor('s_disk_kept', 10).length, 1);
  await prepareSessionStorage('s_disk_kept'); await writeFile(join(kept.tmp, 'later.txt'), 'new files must survive retries');
  assert.deepEqual((await post('/api/product/storage/cleanup', { plan_id: plan.id, confirm: true })).body, receipt,
    'a retry replays the exact receipt, including the original measured disk delta');
  assert.equal(await exists(join(kept.tmp, 'later.txt')), true, 'single-use authority cannot delete later files');
  const deleted = await fixture('s_disk_deleted');
  r = await post('/api/product/storage/plan', { sessions: ['s_disk_deleted'], mode: 'delete' });
  assert.equal(r.status, 200);
  const full = await post('/api/product/storage/cleanup', { plan_id: r.body.id, confirm: true });
  assert.equal(full.body.results[0].deleted, true); assert.equal(store.getSession('s_disk_deleted'), undefined);
  assert.equal(await exists(deleted.artifacts), false); assert.equal(await readFile(join(project, 'keep-code'), 'utf8'), 'important code');
  await fixture('s_disk_running'); store.updateSession('s_disk_running', { status: 'working' });
  assert.equal((await post('/api/product/storage/plan', { sessions: ['s_disk_running'] })).status, 409);
  await fixture('s_disk_recovering'); store.updateSession('s_disk_recovering', { desired_status: 'working' });
  assert.equal((await post('/api/product/storage/plan', { sessions: ['s_disk_recovering'] })).status, 409);
  await fixture('s_disk_stopped', 'operator-stop');
  assert.equal((await post('/api/product/storage/plan', { sessions: ['s_disk_stopped'], mode: 'delete' })).status, 409);
  // Exercise real Git safety, not a mocked "clean" verdict.
  const repo = join(dir, 'repo'); await mkdir(repo);
  const git = args => execFileSync('git', ['-C', repo, ...args], { encoding: 'utf8' });
  git(['init', '-q', '-b', 'main']); git(['config', 'user.name', 'disk fixture']); git(['config', 'user.email', 'fixture@example.invalid']);
  await writeFile(join(repo, 'source.txt'), 'keep source'); git(['add', '.']); git(['commit', '-qm', 'fixture base']);
  store.createProject({ id: 'p_git_disk', name: 'Git fixture', path: repo });
  const { ensureWorktree } = await import('../src/worktrees.js');
  const dirty = await ensureWorktree({ repoPath: repo, sid: 's_disk_dirty', project: { name: 'Git fixture', path: repo } });
  await fixture('s_disk_dirty'); store.updateSession('s_disk_dirty', { project_id: 'p_git_disk', worktree_path: dirty.path, branch: dirty.branch });
  await writeFile(join(dirty.path, 'uncommitted.txt'), 'do not destroy this work');
  assert.equal((await post('/api/product/storage/plan', { sessions: ['s_disk_dirty'], mode: 'delete' })).status, 409);
  assert.equal(await exists(join(dirty.path, 'uncommitted.txt')), true);
  const clean = await ensureWorktree({ repoPath: repo, sid: 's_disk_clean', project: { name: 'Git fixture', path: repo } });
  await fixture('s_disk_clean'); store.updateSession('s_disk_clean', { project_id: 'p_git_disk', worktree_path: clean.path, branch: clean.branch });
  r = await post('/api/product/storage/plan', { sessions: ['s_disk_clean'], mode: 'delete' });
  assert.equal(r.status, 200);
  assert.equal((await post('/api/product/storage/cleanup', { plan_id: r.body.id, confirm: true })).body.ok, true);
  assert.equal(await exists(clean.path), false); assert.equal(await readFile(join(repo, 'source.txt'), 'utf8'), 'keep source');
  const swapped = await fixture('s_disk_swap');
  r = await post('/api/product/storage/plan', { sessions: ['s_disk_swap'] });
  await rm(swapped.root, { recursive: true }); await symlink(project, swapped.root);
  const refusal = await post('/api/product/storage/cleanup', { plan_id: r.body.id, confirm: true });
  assert.equal(refusal.body.ok, false); assert.equal(await exists(join(process.env.AIOS_DATA, 'logs', 's_disk_swap.log')), true, 'all paths preflight before first deletion');
  await fixture('s_disk_resume_race');
  r = await post('/api/product/storage/plan', { sessions: ['s_disk_resume_race'] });
  store.updateSession('s_disk_resume_race', { status: 'working' });
  assert.equal((await post('/api/product/storage/cleanup', { plan_id: r.body.id, confirm: true })).body.ok, false);
  const { withSessionCleanup } = await import('../src/session_cleanup_lock.js');
  const { resume } = await import('../src/sessions.js');
  await withSessionCleanup('s_disk_kept', () => assert.rejects(() => resume('s_disk_kept'), e => e.code === 'session-cleanup-in-progress'));
  process.env.AIOS_DISK_RESERVE_BYTES = '1e30';
  const before = store.listSessions().length;
  r = await post('/api/session', { project_id: 'p_disk', tool: 'codex', task: 'must not launch under pressure' });
  assert.equal(r.status, 507); assert.equal(r.body.code, 'disk-space-critical'); assert.equal(store.listSessions().length, before);
  delete process.env.AIOS_DISK_RESERVE_BYTES;
  console.log(JSON.stringify({ handler: 'real storage plan/cleanup HTTP handlers + private SQLite',
    unconfirmed: 'no deletion', disposable: 'keeps outputs/code/history', killedSessionDelete: 'explicitly confirmed',
    liveAndRecovering: 'blocked', symlinkSwap: 'refused before deletion', realGitWorktree: 'dirty retained / clean removed',
    resumeRace: 'blocked', lowSpaceLaunch: '507 before reservation', liveDataTouched: false }));
  store.db.close(); await rm(dir, { recursive: true, force: true }); process.exit(0);
} catch (error) { console.error(error.stack || error); try { store?.db.close(); } catch {} await rm(dir, { recursive: true, force: true }); process.exit(1); }
