import assert from 'node:assert/strict';
import { createLabelBudget } from '../src/label_budget.js';

let time = 100000, enabled = true, interval = 30000, calls = 0;
const budget = createLabelBudget({ enabled: () => enabled, interval: () => interval, clock: () => time });
assert.equal(budget.ready(), true);
let finish;
const active = budget.run(async () => { calls++; return new Promise(resolve => { finish = resolve; }); });
assert.equal(budget.state().busy, true);
await assert.rejects(() => budget.run(() => { calls++; }), { code: 'LABEL_DEFERRED' });
assert.equal(calls, 1, 'another session does not queue extra model work');
finish('label'); await active;
assert.equal(budget.ready(), false, 'a successful call still imposes a global cadence');
time += 29999;
assert.equal(budget.ready(), false);
time++;
assert.equal(budget.ready(), true);
enabled = false;
await assert.rejects(() => budget.run(() => { calls++; }), { code: 'LABEL_DEFERRED' });
enabled = true;
await assert.rejects(() => budget.run(() => { throw new Error('The model `background/qwen` does not exist.'); }));
assert.equal(budget.state().next_attempt_at, time + 900000, 'the observed missing-model wording stands down for 15 minutes');
time += 900000;
await assert.rejects(() => budget.run(() => { throw new Error('HTTP 429: Background request yielded to interactive traffic'); }));
assert.equal(budget.state().next_attempt_at, time + 240000, 'interactive traffic wins without immediate retries');
time += 240000;
await budget.run(() => 'recovered');
assert.equal(budget.state().failures, 0);
time += 30000;
await assert.rejects(() => budget.run(() => { throw new SyntaxError('Invalid JSON'); }));
assert.equal(budget.state().next_attempt_at, time + 30000);
time += 30000;
await assert.rejects(() => budget.run(() => { throw new SyntaxError('Invalid JSON'); }));
assert.equal(budget.state().next_attempt_at, time + 60000, 'malformed model answers back off exponentially too');
time += 60000;
await budget.run(() => 'recovered');
time += 30000;
interval = 60000;
await budget.run(() => 'slower cadence');
assert.equal(budget.state().next_attempt_at, time + 60000);
console.log('label_budget: no queue, global cadence, missing-model/interactive/JSON failure backoff passed');
