// verify_story_view.mjs — v2 adversarial design-conformance probe for the story view.
// Run AFTER implementation:  node verify_story_view.mjs http://127.0.0.1:8789/session?id=<sid>
// Requires playwright:  npm i -D playwright
//
// v2 changes:
//  - opens a steps expander ITSELF for the computed-style pass (implementations must NOT pre-open one)
//  - fails if any steps body is visible before any click (anti-seeding)
//  - fails if opening a second expander closes the first (anti-accordion)
//  - alpha-aware color comparison (icon tints, ask card rgba)
//  - padding shorthand comparison
// Exits non-zero with findings. The implementing agent is not done until this passes.
// Do NOT edit this file or spec.tokens.json to make it pass.

import { chromium } from 'playwright';
import { readFileSync } from 'fs';

const spec = JSON.parse(readFileSync(new URL('./spec.tokens.json', import.meta.url), 'utf8'));
const url = process.argv[2];
if (!url) { console.error('usage: node verify_story_view.mjs <session-url>'); process.exit(2); }

const findings = [];
const norm = (v) => String(v ?? '').replace(/\s+/g, ' ').trim().toLowerCase();

function parseColor(s) {
  s = String(s || '').trim();
  let m = /^#([0-9a-f]{6})$/i.exec(s);
  if (m) { const n = parseInt(m[1], 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255, 1]; }
  m = /^rgba?\(([^)]+)\)$/i.exec(s);
  if (m) { const p = m[1].split(',').map((x) => parseFloat(x)); return [p[0], p[1], p[2], p[3] == null ? 1 : p[3]]; }
  return null;
}
const cmpColor = (want, got) => {
  const w = parseColor(want), g = parseColor(got);
  if (!w || !g) return norm(want) === norm(got);
  return Math.abs(w[0] - g[0]) <= 1 && Math.abs(w[1] - g[1]) <= 1 && Math.abs(w[2] - g[2]) <= 1 && Math.abs(w[3] - g[3]) <= 0.02;
};
const cmpPx = (want, got) => Math.abs(parseFloat(want) - parseFloat(got)) <= 0.5;
function expand4(str) {
  const a = String(str).trim().split(/\s+/).map(parseFloat);
  if (a.length === 1) return [a[0], a[0], a[0], a[0]];
  if (a.length === 2) return [a[0], a[1], a[0], a[1]];
  if (a.length === 3) return [a[0], a[1], a[2], a[1]];
  return a.slice(0, 4);
}
const cmpPadding = (want, got) => {
  const w = expand4(want), g = expand4(got);
  return w.every((v, i) => Math.abs(v - g[i]) <= 0.5);
};

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
await page.goto(url, { waitUntil: 'load' }); await page.waitForTimeout(6500); // SSE keeps network busy; assertions unchanged

const dc = spec.domContract;

// ---------- 0. anti-seeding: nothing pre-opened ----------
if (await page.$(dc.stepsBody))
  findings.push('BEHAVIOR: a steps peek is open on initial load — spec: all collapsed until the user clicks (no seeding to satisfy style checks)');

// ---------- 1. DOM contract ----------
for (const [name, sel] of Object.entries(dc)) {
  if (name.startsWith('$') || name === 'kinds' || name === 'eventKindAttr') continue;
  if (name === 'stepsBody') continue; // legitimately absent until a click
  if (!(await page.$(sel))) findings.push(`DOM: missing ${name} → selector ${sel}`);
}
const kinds = await page.$$eval(dc.event, (els) => els.map((e) => e.getAttribute('data-kind')));
for (const k of kinds) if (k && !dc.kinds.includes(k)) findings.push(`DOM: unknown event kind "${k}"`);
if (!kinds.length) findings.push('DOM: no story events rendered at all');

// ---------- 2. Computed styles ----------
// Open ONE expander ourselves so steps styles are measurable; close it again afterwards.
const expanders = await page.$$(dc.stepsExpander);
let openedForStyles = false;
if (expanders[0] && !(await page.$(dc.stepsBody))) { await expanders[0].click(); openedForStyles = true; }

for (const [sel, props] of Object.entries(spec.computedStyles)) {
  if (sel.startsWith('$')) continue;
  const el = await page.$(sel);
  if (!el) { findings.push(`STYLE: nothing matches ${sel} (cannot verify)`); continue; }
  const got = await el.evaluate((e, keys) => {
    const cs = getComputedStyle(e); const o = {};
    for (const k of keys) o[k] = cs[k] || (k === 'borderColor' ? cs.borderTopColor : '');
    if (keys.includes('padding')) o.padding = [cs.paddingTop, cs.paddingRight, cs.paddingBottom, cs.paddingLeft].join(' ');
    if (keys.includes('borderColor') && !o.borderColor) o.borderColor = cs.borderTopColor;
    return o;
  }, Object.keys(props));
  for (const [prop, want] of Object.entries(props)) {
    const g = got[prop];
    let ok;
    if (prop === 'padding') ok = cmpPadding(want, g);
    else if (/color/i.test(prop)) ok = cmpColor(want, g);
    else if (/(size|height|width|radius)/i.test(prop) && /px$/.test(String(want))) ok = cmpPx(want, g);
    else if (prop === 'lineHeight') ok = cmpPx(parseFloat(want) * parseFloat(got.fontSize || 13), g) || Math.abs(parseFloat(g) / parseFloat(got.fontSize || '13px') - parseFloat(want)) < 0.15;
    else ok = norm(g).includes(norm(want));
    if (!ok) findings.push(`STYLE: ${sel} { ${prop}: expected ${want}, got ${g} }`);
  }
}
if (openedForStyles && expanders[0]) {
  await expanders[0].click();
  if (await page.$(dc.stepsBody)) findings.push('INTERACTION: expander does not collapse again after the style pass');
}

// ---------- 3. Interactions ----------
// 3a. toggle: story <-> terminal swaps panels
await page.click(dc.toggleTerminal);
if (await page.$eval(dc.panel, (e) => !!e.offsetParent).catch(() => false))
  findings.push('INTERACTION: terminal mode still shows the story panel');
await page.click(dc.toggleStory);
if (!(await page.$eval(dc.panel, (e) => !!e.offsetParent).catch(() => false)))
  findings.push('INTERACTION: switching back to story does not restore the panel');

// 3b. expander opens and closes
if (!expanders.length) findings.push('INTERACTION: no steps expander rendered');
else {
  await expanders[0].click();
  if (!(await page.$(dc.stepsBody))) findings.push('INTERACTION: expander click does not reveal steps');
  else {
    // 3c. anti-accordion: a second expander must not close the first
    if (expanders[1]) {
      await expanders[1].click();
      const openCount = (await page.$$(dc.stepsBody)).length;
      if (openCount < 2) findings.push('INTERACTION: accordion behavior detected — opening one steps peek closed another (spec: independent per block)');
      await expanders[1].click();
    }
    await expanders[0].click();
    if (await page.$eval(dc.stepsBody, (e) => !!e.offsetParent).catch(() => false))
      findings.push('INTERACTION: expander does not collapse again');
  }
}

// 3d. ask buttons POST to the input endpoint
const askOpt = await page.$(dc.askOptions);
if (askOpt) {
  const [req] = await Promise.all([
    page.waitForRequest((r) => /\/api\/session\/.+\/(input|type)/.test(r.url()) && r.method() === 'POST', { timeout: 3000 }).catch(() => null),
    askOpt.click(),
  ]);
  if (!req) findings.push('INTERACTION: ask option click did not POST to the session input endpoint');
}

// 3e. hover state on expander
const exp2 = (await page.$$(dc.stepsExpander))[0];
if (exp2) {
  const before = await exp2.evaluate((e) => getComputedStyle(e).color);
  await exp2.hover();
  const after = await exp2.evaluate((e) => getComputedStyle(e).color);
  if (before === after) findings.push('INTERACTION: steps expander has no hover state');
}

// 3f. persistence: reload keeps the chosen mode
await page.click(dc.toggleTerminal);
await page.reload({ waitUntil: 'load' }); await page.waitForTimeout(5000);
if (await page.$eval(dc.panel, (e) => !!e.offsetParent).catch(() => false))
  findings.push('INTERACTION: log-view choice does not persist across reload');

await browser.close();

if (findings.length) {
  console.error(`\n✗ ${findings.length} conformance finding(s):\n` + findings.map((f) => '  - ' + f).join('\n'));
  process.exit(1);
}
console.log('✓ story view conforms to spec.tokens.json v2 (DOM, styles, interactions, anti-gaming)');
