// verify_shell_v3.mjs — whole-shell conformance probe (extends verify_story_view.mjs, which stays
// authoritative for the story view). Give it every page of the app; checks auto-apply per page:
//
//   node verify_shell_v3.mjs http://127.0.0.1:8789/ http://127.0.0.1:8789/session?id=<sid> <settings-url> ...
//
// Exits non-zero with findings. Do NOT edit this file to make it pass.

import { chromium } from 'playwright';

const urls = process.argv.slice(2);
if (!urls.length) { console.error('usage: node verify_shell_v3.mjs <url> [<url> ...]'); process.exit(2); }

const findings = [];
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });

for (const url of urls) {
  await page.goto(url, { waitUntil: 'networkidle' }).catch((e) => findings.push(`${url}: failed to load — ${e.message}`));
  const body = (await page.textContent('body').catch(() => '')) || '';
  const tag = (m) => findings.push(`${url}: ${m}`);

  // ---- session page checks ----
  if (await page.$('[data-story-toggle]')) {
    // B1: old supervisor segmented must be gone (design: compact `co-pilot ▾` select row)
    const segmented = await page.evaluate(() => {
      const btns = [...document.querySelectorAll('button')].map((b) => b.textContent.trim().toLowerCase());
      return ['off', 'observe', 'co-pilot', 'autopilot'].every((m) => btns.includes(m));
    });
    if (segmented) tag('supervisor panel still uses the Off/Observe/Co-pilot/Autopilot segmented — replace with the compact `co-pilot ▾` inline select row (blue #79b8ff, mono 12px) per MAIN-DESIGN-README');
    // B2: THE CONTRACT chip was removed from the design
    if (/THE CONTRACT/.test(body)) tag('“THE CONTRACT” chip still rendered on the task card — removed in the design (the TASK CARD label already says it)');
    // A-regression tripwires (parser fixes must be live)
    if (/<tool_use_error>/.test(body)) tag('raw <tool_use_error> tags visible in story bodies — r4 parser not applied');
    if (/\d{3,}(\.\d+)?\s*hr active/.test(body)) tag('rollup still shows absurd active-hours (wall-clock, not activity) — r4 rollup not applied');
    if (/\b\d{2,}\s*unresolved fails\b/.test(body)) tag('rollup still counts all-history fails — r4 rollup not applied');
    // fail events must not be titled bare "fail"
    const bareFail = await page.$$eval('[data-story-ev="fail"] .story-title', (els) => els.some((e) => e.textContent.trim().toLowerCase() === 'fail'));
    if (bareFail) tag('fail events titled literally "fail" — parser should emit a human title ("Hit a snag")');
    // mini-rail dots: collapse, expect one dot per live session
    const collapse = await page.$('[data-rail-collapse]');
    if (collapse) {
      await collapse.click();
      await page.waitForTimeout(400);
      const railRows = await page.$$eval('#session-rail-list a[href*="session?id="]', (a) => a.length).catch(() => 0);
      const dots = await page.$$eval('#mini-dots a', (a) => a.length).catch(() => 0);
      if (railRows > 0 && dots === 0) tag('collapsed mini-rail shows no session dots while the full rail has sessions — renderMiniDots not firing on collapse');
      await collapse.click().catch(() => {});
    }
  }

  // ---- desktop/inbox checks ----
  if (await page.$('.dk-card, #dk-cards')) {
    const h1 = await page.$('.dk-page-head h1');
    if (h1) {
      const fs = await h1.evaluate((e) => getComputedStyle(e).fontSize);
      if (Math.abs(parseFloat(fs) - 19) > 0.5) tag(`page h1 is ${fs}, spec is 19px`);
    }
    // B3: reply editor hidden until Reply is clicked
    const openReplies = await page.$$eval('.dk-reply', (els) => els.filter((e) => !e.hidden && e.offsetParent).length).catch(() => 0);
    if (openReplies > 0) tag(`${openReplies} inbox reply editor(s) open on load — spec: hidden until the Reply button is clicked`);
    // C1: cards must not ship raw TUI chrome — derive the question, not the terminal tail
    if (/bypass permissions on|context used|shift\+tab to cycle/.test(body)) tag('inbox cards contain raw TUI scrollback (“bypass permissions on…”, “100% context used”) — serve the derived question (last unanswered ask from the story parser) instead of the terminal tail');
    // B4: sidebar chip/status collision + URL-as-name
    const collide = await page.evaluate(() => {
      for (const row of document.querySelectorAll('.dk-sess-l1')) {
        const chip = row.querySelector('.dk-agent'), st = row.querySelector('.dk-status');
        if (chip && st) { const a = chip.getBoundingClientRect(), b = st.getBoundingClientRect(); if (a.right > b.left - 2 && a.left < b.right) return true; }
      }
      return false;
    });
    if (collide) tag('sidebar session rows: agent chip overlaps the status word — flex row needs gap/min-width so “claude” and “Working” never collide');
    const urlName = await page.$$eval('.dk-sess-l1 b', (els) => els.some((e) => /https?:\/\//.test(e.textContent))).catch(() => false);
    if (urlName) tag('sidebar session name renders a URL — name should be the session/project short name; the task snippet belongs on line 2');
  }

  // ---- settings checks ----
  if (/Agents & sign-in/.test(body)) {
    // B5: one card per CLI — login state and install state must not appear as duplicate contradictory rows
    for (const cli of ['claude', 'codex', 'antigravity', 'agy']) {
      const re = new RegExp(cli + '[^\\n]{0,90}LOGGED IN', 'i');
      const re2 = new RegExp(cli + '\\s+not found', 'i');
      if (re.test(body) && re2.test(body)) tag(`settings lists “${cli}” twice — LOGGED IN in one row and “not found” in another. Spec: ONE card per CLI: name · version (or not found + install) · login chip · token expiry · Re-login`);
    }
    if (/No API providers yet\./.test(body) && /built-in/.test(body)) tag('“No API providers yet.” renders below a non-empty provider list — drop the empty-state when rows exist');
  }
}

await browser.close();
if (findings.length) {
  console.error(`\n✗ ${findings.length} shell finding(s):\n` + findings.map((f) => '  - ' + f).join('\n'));
  process.exit(1);
}
console.log('✓ shell conforms (supervisor panel, inbox, sidebar, settings, story tripwires)');
